anon-aadhaar/anon-aadhaar

.gitignore, README.md, package.json, script/setup-dev.sh
Resolve #2 
DONE: 
- Update build script, made project easier to setup 
- Update instruction in README.md.
=> Update build script and README.md

.github/workflows/01-workflow.yaml, package.json
=> Fix github CI

README.md, package.json, script/setup-dev.sh, yarn.lock
Resolve #15. Compatible with old [anon-aadhaar](https://github.com/dmpierre/anon-adhaar) source code.
Output: 
- signed.pdf with signature create by certificate.cer. Both files save in `build` folder.
=> The script use for create pdf with sign and certificate

src/utils.ts
Note: 
- https://www.adobe.com/devnet-docs/acrobatetk/tools/DigSig/Acrobat_DigitalSignatures_in_PDF.pdf
Resolve #10
=> Extract signature from pdf

package.json, src/pcd.ts, src/utils.ts, yarn.lock
Fixed some things in the package in order to be able to verify a proof in the Zupass repo.
=> fixed serialize function

script/setup-dev.sh
Use assign array statement in circom 2.0.
=> Update circom rsa verify

.github/workflows/01-workflow.yaml, .gitmodules, CHANGELOG.md, circuits/README.md, circuits/bigint.circom, circuits/bigint_func.circom, circuits/fp.circom, circuits/main.circom, circuits/rsa.circom, package.json, script/setup-dev.sh, script/utils.sh, src/CardBody.tsx, src/pcd.ts, src/prover.ts, src/types.ts, test/pcd.test.ts, yarn.lock
=> Feat/repleace RSA circuit

CHANGELOG.md, package.json, packages/anon-aadhaar-contracts/package.json, packages/anon-aadhaar-pcd/package.json, packages/anon-aadhaar-react/package.json, yarn.lock
=> fix dependencies issues

package.json, packages/anon-aadhaar-contracts/package.json, packages/anon-aadhaar-pcd/package.json, packages/anon-aadhaar-react/package.json
Upgrade version before publishing
=> upgrade to v0.1.8

packages/anon-aadhaar-pcd/src/constants.ts
=> fix(chore): modified artifacts url

README.md
=> Recomment install qpdf

CHANGELOG.md, package.json, packages/anon-aadhaar-contracts/package.json, packages/anon-aadhaar-pcd/package.json, packages/anon-aadhaar-react/package.json, packages/anon-aadhaar-react/src/components/LogInWithAnonAadhaar.tsx, packages/anon-aadhaar-react/src/components/ProveButton.tsx, packages/anon-aadhaar-react/src/components/ProveModal.tsx, packages/anon-aadhaar-react/src/util.ts
Some UI/UX changes.
It also fix Solidity files npm publishing issue.
=> fix(chore): UI improvments + UX fix

packages/anon-aadhaar-contracts/package.json, packages/anon-aadhaar-pcd/package.json, packages/anon-aadhaar-react/package.json
=> postversion

packages/anon-aadhaar-pcd/script/setup-dev.sh
Fixed a typo on the `setup-dev.sh` with a bad capitalization.
=> bug fix: Fixed typo on setup-dev.sh command

package.json, packages/circuits/package.json, packages/circuits/scripts/generateInput.ts, packages/circuits/test/aadhaar-verifier.test.ts, packages/circuits/tsconfig.json, packages/contracts/package.json, packages/contracts/tsconfig.json, packages/core/package.json, packages/core/src/generateArgs.ts, packages/react/package.json, packages/react/tsconfig.json, yarn.lock
Small fix of the zk-email helpers integration
=> fix(chore): zk email/helpers

packages/contracts/deployed-contracts/scroll-sepolia.json, packages/contracts/hardhat.config.ts
Deployed AnonAadhaar contracts on sepolia scroll.
```
{
"testPublicKey": {
"VerifierTest": "0x45199Aa9C90dC945D0710Ce6d5166F9fb8263f04",
"AnonAadhaarTest": "0xbe4ce954Cb0f6b51E86ADa0195055CfB502380Ad",
"AnonAadhaarVote": "0x57a56f6515023C68ad7aeCeF0e81A4E0B21D39cA"
},
"productionPublicKey": {
"Verifier": "0xA09E07Cc47eF94eF56eC5DcF338379AD86A2DF4B",
"AnonAadhaar": "0x31c3041888bA7d27c92a61849fE24152D81b4A3e",
"AnonAadhaarVote": "0xFF78fD5bCbBA425ee1770d1BAf473EE41a5336be"
}
}
```
=> feat: deployed on scroll sepolia

packages/circuits/tsconfig.json, yarn.lock
Describe why this issue should be fixed and link to any relevant design docs, issues or other relevant items.
Describe the changes being made in 1-2 concise sentences.
=> fix: missing files

packages/circuits/scripts/build.sh, packages/circuits/scripts/generateInput.ts, packages/circuits/src/helpers/extractor.circom, packages/circuits/tsconfig.json
Fix GT byte limit in age extractor
Describe the changes being made in 1-2 concise sentences.
=> Fix GT byte limit in age extractor

CHANGELOG.md, package.json, packages/circuits/package.json, packages/contracts/package.json, packages/core/package.json, packages/core/src/qrGenerator.ts, packages/react/package.json, packages/react/src/hooks/useProver.ts
- fix timestamp in QR code generator (UTC to IST based)
- fix returned type in useProver hook
=> fix: qr generator

README.md
=> fix: readme.md: fix typo: protocol instead of procotocol

packages/circuits/scripts/generateTestData.ts, packages/core/src/qrGenerator.ts, packages/core/src/utils.ts
Change the `generateTestData.ts` script to generate signed data with different photos and then compute different nullifiers.
=> feat: custom test photo

.github/PULL_REQUEST_TEMPLATE.md, packages/core/src/utils.ts
Utility for decoding bigint to string is needed for smooth SDK integration, in reference to [this](https://github.com/anon-aadhaar/anon-aadhaar/issues/221) issue.
Utility function for decoding BigInt to String is added.
PR Template change set URL correction.
=> Decode Reveal to UTF-8 Utility Added

CHANGELOG.md, package.json, packages/circuits/package.json, packages/contracts/package.json, packages/core/package.json, packages/react/package.json, packages/react/src/components/ProveModal/Modal.tsx, packages/react/test/hook.test.tsx, yarn.lock
Enable mobile browser proving and add responsive styles for mobile devices. Also, perform a version bump.
=> Add Mobile Browser Proving Support
